app/models/post.py
from datetime import datetime
from ..extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.String(250))
    subject = db.Column(db.String(250))
    student = db.Column(db.String(250))
    date = db.Column(db.DateTime, default=datetime.now())
    

app/models/user.py
from ..extensions import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

app/__init__.py
from flask import Flask
from .extensions import db, migrate
from .config import Config

from .routes.user import user
from .routes.post import post

def create_app(config_class=Config):
    app = Flask(__name__)
    
    app.config.from_object(config_class)
    
    app.register_blueprint(user)
    app.register_blueprint(post)
    
    db.init_app(app)
    migrate.init_app(app, db)
    
    with app.app_context():
        db.create_all()
    
    return app

app/routes/post.py
from flask import Blueprint, render_template, request, redirect
from ..extensions import db
from ..models.post import Post

post = Blueprint('post', __name__)

@post.route('/', methods=['POST', 'GET'])
def all():
    posts = Post.query.order_by(Post.id).all()
    return render_template('post/all.html', posts=posts)

@post.route('/post/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':
        teacher = request.form['teacher']
        subject = request.form['subject']
        student = request.form['student']
        
        post = Post(teacher=teacher, subject=subject, student=student)
        
        try:
            db.session.add(post)
            db.session.commit()
            
            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/create.html')
    
@post.route('/post/<int:id>/update', methods=['POST', 'GET'])
def update(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.teacher = request.form['teacher']
        post.subject = request.form['subject']
        post.student = request.form['student']
        
        try:
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/update.html', post=post)
    
@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
def delete(id):
    post = Post.query.get(id)
    
    try:
        db.session.delete(post)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))

app/routes/user.py
from flask import Blueprint
from ..extensions import db
from ..models.user import User

user = Blueprint('user', __name__)

@user.route('/user/<name>')
def create_user(name):
    user = User(name=name)
    db.session.add(user)
    db.session.commit()
    return 'Success'

app/templates/main/_footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
    </ul>
    <p class="text-center">© 2025 Company, Inc</p>
</footer>

app/templates/main/_header.html
<header
    class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0"> <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none"> <svg
                class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
                <use xlink:href="#bootstrap"></use>
            </svg> </a> </div>
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{{ url_for('post.all')}}" class="nav-link px-2 link-secondary">Главная</a></li>
        <li><a href="{{ url_for('post.create')}}" class="nav-link px-2">Добавить тему</a></li>
        <li><a href="#" class="nav-link px-2">FAQs</a></li>
        <li><a href="#" class="nav-link px-2">About</a></li>
    </ul>
    <div class="col-md-3 text-end"> <button type="button" class="btn btn-outline-primary me-2">Login</button> <button
            type="button" class="btn btn-primary">Sign-up</button> </div>
</header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <header class="header">{% include 'main/_header.html' %}</header>

        <div class="page">
            <main class="content">
                <h1>{{ self.title() }}</h1>
                {% block content %}{% endblock %}
            </main>
            <footer class="py-3 my-4">{% include 'main/_footer.html' %}</footer>
        </div>

        <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    </body>
</html>

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %}Темы{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css')}}">
{% endblock %}

{% block content %}
<div class="table-responsive custom-table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th scope="col">Преподаватель</th>
                <th scope="col">Тема</th>
                <th scope="col">Студент</th>
                <th scope="col">Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr scope="row">
                <td>{{ post.teacher }}</td>
                <td>{{ post.subject }}</td>
                <td>{{ post.student }}</td>
                <td>
                    <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-secondary">Ред.</a>
                    <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger">Удалить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}Добавление темы{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="teacher" type="text" placeholder="ФИО преподавателя" class="form-control">
    <input name="subject" type="text" placeholder="Предмет" class="form-control">
    <input name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value="Добавить" type="submit" class="btn-success">
</form>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}Редактирование темы {{ post.id }}{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{ post.teacher }}" name="teacher" type="text" placeholder="ФИО преподавателя" class="form-control">
    <input value="{{ post.subject }}" name="subject" type="text" placeholder="Предмет" class="form-control">
    <input value="{{ post.student }}" name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value="Изменить" type="submit" class="btn-success">
</form>
{% endblock %}